http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
  apiAccount: "account-customerwebapihttpsystem-9c6e37.5sc6y6-1.usa-e2.cloudhub.io"
  apiProduct: "products-webapisystem-9c6e37.5sc6y6-1.usa-e2.cloudhub.io"
  
american:
  host: "training4americanwsproxymuleappsamuel.us-e2.cloudhub.io"
  port: "80"
  basepath: ""
  protocol: "HTTP"
  client_id: "93ecd1dcaff44bd9b242880f7fd6383a"
  client_secret: "966D0054Dd8C43B6B2Fd015491CbF42E"
  
training:
  host: "mu.mule-training.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"

delta:
  wsdl: "http://mu.mule-training.com/delta?wsdl"
  service: "TicketServiceService"
  port: "DeltaFlightsServiceImplPort"
sfdc4: 
  username: "samuel.chapman-matos@viseo.com"
  password: "Catedra251289"
  token: "1scqYSgvjtUhByVNetWWytjUc"
sfdc1:
  username: "samuel.chapman-matos@empathetic-koala-bl9vmk.com"
  password: "Catedra251289*"
  token: "9sunZOQyzZjeBaEYjUaCoHZ6"
sfdc:
  username: "samuelchapmanmatos12@gmail.com"
  password: "Catedra251289"
  token: "ITlEFNIuB6DZ9ZMgt0qoyyD89"
sfdc2:
  username: "samuelchapmanmatos13@gmail.com"
  password: "Catedra251289"
  token: "XOue0OUYiuWrKvnWdlPd84Yl"
sfdc3:
  username: "samuelchapmanmatos@yahoo.com"
  password: "Catedra251289"
  token: "zifLwNbt5FdD4AAmli18RfyOc"
  